apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: movie
          image: movie:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
            - containerPort: 8091
          env:
            - name: JAEGER_AGENT_HOST
              value: "jaeger"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: movie
  namespace: default
spec:
  selector:
    app: movie
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8083
    - name: metrics
      protocol: TCP
      port: 8091
      targetPort: 8091
  type: ClusterIP
