apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie
  template:
    metadata:
      labels:
        app: movie
    spec:
      containers:
        - name: movie
          image: movie:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
          env:
            - name: JAEGER_AGENT_HOST
              value: "jaeger"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
