api:
  port: 8081
postgres:
  user: "postgres"
  password: "Password@123"
  host: "postgres"
  dbname: "movieapp"
serviceDiscovery:
  consul:
    address: consul:8500
jaeger:
  url: http://jaeger:14268/api/traces
